version: '3.7'

services:
  careerwise-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careerwise-frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
